export enum ReportSubject {
    ABANDONO = 'ABANDONO',
    MAUS_TRATOS = 'MAUS_TRATOS',
    FALTA_DE_ALIMENTACAO = 'FALTA_DE_ALIMENTACAO',
    FALTA_DE_AGUA = 'FALTA_DE_AGUA',
    CRIACAO_IRREGULAR = 'CRIACAO_IRREGULAR',
    VENDA_ILEGAL = 'VENDA_ILEGAL',
    OUTROS = 'OUTROS',
}